In [26]:
import numpy as np
print("Versão do Numpy", np.__version__)
print("")

print("Numpy - é uma biblioteca fundamental para a computação científica em python, amplamente utilizada para a realizaçr operações numéricas de forma  eficiente e rápida.")
print("Numpy oferece suporte a arrays e matrizes multidimensionais, junto com o uma coleção de funções metemáticas para operar nesses arrays.")
print("Array de dados com Numpy")
print("")
print("===========================================================================")
print("")
np_array = np.array([1, 2, 3, 4, 5])
print("Array Numpy:", np_array)

print("")
print("===========================================================================")
print("")

print("Calulando a média")
media = np.mean(np_array)  # Cálculo da média
print("Média dos valores:", media)

print("")
print("===========================================================================")
print("")
print("Calulando a mediana")
mediana = np.median(np_array)  # Cálculo da mediana
print("Mediana dos valores:", mediana)

print("")
print("===========================================================================")
print("")
print("Calulando o desvio padrão")
desvio_padrao = np.std(np_array)  # Cálculo do desvio padrão
print("Desvio Padrão dos valores:", desvio_padrao)

print("")
print("===========================================================================")
print("")

matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matriz Numpy:\n", matriz)
print("")
print("===========================================================================")
print("")
print("calculando a transposta da matriz")
transposta = np.transpose(matriz)
print(transposta)
print("")
print("===========================================================================")
print("")
print("Número aleatórios de uma matrixz 3x3 de 2 dígitos")
random = np.random.rand(3,3).round(2)
print("Números aleatórios:", random)
print("")
print("===========================================================================")
print("")
print("Número aleatórios de um array de 5 posições de 2 dígitos")
random = np.random.rand(5).round(2)
print("Números aleatórios:", random)
print("")
print("===========================================================================")
print("")
print("Número aleatórios de um array de 5 posições não arredondados")
random = np.random.rand(5)
print("Números aleatórios:", random)
print("")
print("===========================================================================")
print("")
print("Número aleatórios de um array de 5 posições de 2 dígitos")
matrizAleatoria = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60])
random = np.random.choice(matrizAleatoria, size=6, replace=False)
print("Números aleatórios:", random)
print("")
print("===========================================================================")
print("")
print("Realizar operações de àlgebra linear com Numpy ")
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
soma = np.add(a, b)
print("Soma de matrizes:\n", soma)
print("")
print("===========================================================================")
print("")
dot = np.dot(a,b)
print("Produto de matrizes:\n", dot)
print("")
print("===========================================================================")
print("")
print("Elevar todos os elementos da matriz ao quadrado")
matrizQuadrada = np.power(matriz,2)
print("Matriz ao quadrado:\n", matrizQuadrada)
print("")
print("===========================================================================")
print("")
print("Raiz quadrada de todos os elementos da matriz")
matrizRaiz = np.sqrt(matrizQuadrada)
print("Matriz Raiz Quadrada:\n", matrizRaiz)




Versão do Numpy 2.2.6

Trabalhando com Numpy: Ela está voltadada para cálculos de dados matemáticos
Array de dados com Numpy


Array Numpy: [1 2 3 4 5]


Calulando a média
Média dos valores: 3.0


Calulando a mediana
Mediana dos valores: 3.0


Calulando o desvio padrão
Desvio Padrão dos valores: 1.4142135623730951


Matriz Numpy:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


calculando a transposta da matriz
[[1 4 7]
 [2 5 8]
 [3 6 9]]


Número aleatórios de uma matrixz 3x3 de 2 dígitos
Números aleatórios: [[0.74 0.34 0.74]
 [0.24 0.47 0.14]
 [0.06 0.76 0.73]]


Número aleatórios de um array de 5 posições de 2 dígitos
Números aleatórios: [0.63 0.4  0.09 0.2  0.86]


Número aleatórios de um array de 5 posições não arredondados
Números aleatórios: [0.24376529 0.56224602 0.69779479 0.77704753 0.86433525]


Número aleatórios de um array de 5 posições de 2 dígitos
Números aleatórios: [46  8 41 58 20 17]


Realizar operações de àlgebra linear com Numpy 
Soma de matrizes:
 [[ 6  8]
 [10 12]]


Produto de ma